title: "Genome Ark"
email: "ola.pawlowska@gmail.com"
description: "Welcome to the Genome Ark Species Database! This site provides detailed information on various species, their taxonomy, and sequenced genomic resources. Explore in-depth data about different organisms, discover their genetic sequences, and access resources for research and study. The Genome Ark aims to be a comprehensive hub for genomic data, helping researchers, scientists, and enthusiasts alike in their quest to understand the diversity of life on Earth."
baseurl: "/genome-ark"  # lub pusta wartość jeśli repozytorium jest na głównym poziomie
url: "https://ola5670.github.io"
twitter_username: "jekyllrb"
github_username: "jekyll"
author: "Aleksandra Pawłowska" 

plugins:
  - jekyll-feed
markdown: kramdown
highlighter: rouge
theme: minima

# Collections
collections:
  species:
    output: true

include:
  - _layouts
  - _includes

permalink: pretty

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
